on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  pyinstaller-build-win:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'src/build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'codeforces-practice-tools-win-beta.exe'
          options: -F,--name "CodeforcesPracticeTools"
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'src/build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'codeforces-practice-tools-ubuntu-beta'
          options: -F,--name "CodeforcesPracticeTools"
  pyinstaller-build-macos:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'src/build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'codeforces-practice-tools-osx-beta'
          options: -F,--name "CodeforcesPracticeTools"
